# Generated by Django 3.2.13 on 2022-05-03 23:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='labels',
        ),
        migrations.AddField(
            model_name='label',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
