# Generated by Django 3.2.13 on 2022-05-04 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20220504_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='labels', to=settings.AUTH_USER_MODEL),
        ),
    ]
